version: '2'
services:
  # MySQL
  mysqld:
    #env_file: .env
    image: mysql:5.7
    container_name: mysqld
    ports:
      - "3306:3306"
    volumes:
      - /Users/hy/work/docker-env/projects/mysql/conf:/etc/mysql/conf.d
      - /Users/hy/work/docker-env/projects/python3/django/db_data:/var/lib/mysql
      - /Users/hy/work/docker-env/projects/mysql/init.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiromaily
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: 12345678
  django:
    build:
      context: .
    image: django-py3:v1.0
    container_name: django
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - .:/code
    links:
      - mysqld:mysql-server
    depends_on:
      - mysqld
    stdin_open: true
    tty: true
    restart: always
    command: bash
    #command: python manage.py runserver 0.0.0.0:8080
